### ISSUE TITLE
"TypeError: a float is required" in Python 2.7

### ISSUE THREAD

**Issue by ducalpha** [vzhong/embeddings#1]
I tried to use embeddings on Python 2.7 but got the following error:
```  
  File embeddings/embeddings/glove.py", line 58, in emb
    g = self.lookup(word)
  File "embeddings/embedding.py", line 182, in lookup
    return array('f', q[0]).tolist() if q else None
TypeError: a float is required
```

The above error does not show when I ran in Python 3.6.

**Comment by ducalpha** [comment]
I created the database in Python 3 but read the database in Python 2. Is it possible that the compatibility caused the issue?

**Comment by vzhong** [comment]
I'm sorry! There is no plan to support python 2. If you'd like to contribute a fix, please make a pull request.
