### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by Hayat2018** [vzhong/embeddings#4]
embeddings = [glove embedding(), kazuma char embedding()]
generates a memory error on my system having 4Gb on installed memory.  What is the memory requirements to run embeedings?

**Comment by Hayat2018** [comment]
Even this also generates Memory Error 
from embeddings import GloveEmbedding, FastTextEmbedding, KazumaCharEmbedding, ConcatEmbedding

g = GloveEmbedding('common_crawl_840', d_emb=300, show_progress=True)

**Comment by vzhong** [comment]
Hi @Hayat2018 from a first glance the DB files for common crawl is around 3GB. I would use at least 8GB.

**Comment by Hayat2018** [comment]
Absolutely Correct. Thank you. That solved my problem.
